stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: |-
        mvn clean install org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar \
          -Dsonar.host.url=${SONAR_HOST} \
          -Dsonar.login=${SONAR_KEY}
    envFrom:
    - sourceName: sonar
      sourceKey: url
      targetKey: SONAR_HOST
    - sourceName: sonar
      sourceKey: token
      targetKey: SONAR_KEY
notification: {}
