stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: |-
        mkdir -p /root/.m2 && mv settings.xml /root/.m2/
        mvn clean install org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar \
          -Dsonar.host.url=${SONAR_HOST} \
          -Dsonar.login=${SONAR_KEY} \
          -Dsonar.projectName=maven_scan1
    env:
      NEXUS_HOST: http://repo-nexus.repo-nexus:8081
      NEXUS_TOKEN: admin123
    envFrom:
    - sourceName: sonar
      sourceKey: url
      targetKey: SONAR_HOST
    - sourceName: sonar
      sourceKey: token
      targetKey: SONAR_KEY
- name: push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 127.0.0.1:34646
notification: {}
